/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.DBModel;
import model.IModel;

/**
 *
 * @author Bodnár Tamás <tms.bodnar@gmail.com> | www.kalandlabor.hu
 */
public class Foablak extends javax.swing.JFrame {
        IModel model;
    /**
     * Creates new form Foablak
     */
    public Foablak() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Könyvtári nyilvántartás");
        String connUrl = "jdbc:mysql://localhost:3306/konyvtar";
        String user = "root";
        String pass = "1234";

        try {
            Connection conn = DriverManager.getConnection(connUrl, user, pass);
            model = new DBModel(conn);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mbFajl = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mbAdatok = new javax.swing.JMenu();
        jmKonyvek = new javax.swing.JMenuItem();
        jmTagok = new javax.swing.JMenuItem();
        jmKolcsonzes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbFajl.setText("Fájl");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Kilépés");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mbFajl.add(jMenuItem1);

        jMenuBar1.add(mbFajl);

        mbAdatok.setText("Adatok");

        jmKonyvek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jmKonyvek.setText("Könyvek");
        jmKonyvek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKonyvekActionPerformed(evt);
            }
        });
        mbAdatok.add(jmKonyvek);

        jmTagok.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmTagok.setText("Tagok");
        jmTagok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTagokActionPerformed(evt);
            }
        });
        mbAdatok.add(jmTagok);

        jmKolcsonzes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jmKolcsonzes.setText("Kölcsönzés / Visszavét");
        jmKolcsonzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmKolcsonzesActionPerformed(evt);
            }
        });
        mbAdatok.add(jmKolcsonzes);

        jMenuBar1.add(mbAdatok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(model != null){
            try {
                model.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Adatbázis hiba!", JOptionPane.ERROR_MESSAGE);
            }
        }
        System.exit(0);      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmKonyvekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKonyvekActionPerformed
        KonyvekDialog kd = new KonyvekDialog(this, true, model);
        kd.setVisible(true);
    }//GEN-LAST:event_jmKonyvekActionPerformed

    private void jmTagokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTagokActionPerformed
        TagokDialog td = new TagokDialog(this, true, model);
        td.setVisible(true);
    }//GEN-LAST:event_jmTagokActionPerformed

    private void jmKolcsonzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmKolcsonzesActionPerformed
        KolcsonzesDialog kd = new KolcsonzesDialog(this, true, model);
        kd.setVisible(true);
    }//GEN-LAST:event_jmKolcsonzesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmKolcsonzes;
    private javax.swing.JMenuItem jmKonyvek;
    private javax.swing.JMenuItem jmTagok;
    private javax.swing.JMenu mbAdatok;
    private javax.swing.JMenu mbFajl;
    // End of variables declaration//GEN-END:variables
}
