/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Konyv;

/**
 *
 * @author Bodnár Tamás <tms.bodnar@gmail.com> | www.kalandlabor.hu
 */
public class jdKonyvSzerkeszt extends javax.swing.JDialog {
        private Konyv konyv;
        private boolean mentes;

    public Konyv getKonyv() {
        return konyv;
    }

    public boolean isMentes() {
        return mentes;
    }
    /**
     * Creates new form jdKonyvSzerkeszt
     */
    public jdKonyvSzerkeszt(java.awt.Frame parent, boolean modal, Konyv konyv) {
        super(parent, modal);
        initComponents();
        this.konyv = konyv;
        this.mentes = false;
        if (konyv == null){
            setTitle("Új könyv felvitele.");
        }
        setTitle("Könyv szerkesztése");
       jtSzerzo.setText(konyv.getSzerzo());
       jtCim.setText(konyv.getCim());
       jtOldalszam.setText(konyv.getOldalszam()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jlSzerzo = new javax.swing.JLabel();
        jlcim = new javax.swing.JLabel();
        jtSzerzo = new javax.swing.JTextField();
        jtCim = new javax.swing.JTextField();
        jbMentes = new javax.swing.JButton();
        jbMegsem = new javax.swing.JButton();
        jlOldalszam = new javax.swing.JLabel();
        jtOldalszam = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlSzerzo.setText("Szerző:");

        jlcim.setText("Cím:");

        jbMentes.setText("Mentés");
        jbMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMentesActionPerformed(evt);
            }
        });

        jbMegsem.setText("Mégsem");
        jbMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMegsemActionPerformed(evt);
            }
        });

        jlOldalszam.setText("Oldalszám:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSzerzo)
                    .addComponent(jlcim)
                    .addComponent(jlOldalszam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtCim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbMentes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtOldalszam, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbMegsem))
                            .addComponent(jtSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSzerzo)
                    .addComponent(jtSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcim)
                    .addComponent(jtCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtOldalszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOldalszam)
                    .addComponent(jbMegsem))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbMegsemActionPerformed

    private void jbMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMentesActionPerformed
        mentes = true;
        if (konyv == null){
            konyv = new Konyv();
        }
        konyv.setSzerzo(jtSzerzo.getText());
        konyv.setCim(jtCim.getText());
        konyv.setOldalszam(Integer.parseInt(jtOldalszam.getText()));
        setVisible(false);
        
    }//GEN-LAST:event_jbMentesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbMegsem;
    private javax.swing.JButton jbMentes;
    private javax.swing.JLabel jlOldalszam;
    private javax.swing.JLabel jlSzerzo;
    private javax.swing.JLabel jlcim;
    private javax.swing.JTextField jtCim;
    private javax.swing.JTextField jtOldalszam;
    private javax.swing.JTextField jtSzerzo;
    // End of variables declaration//GEN-END:variables
}
