/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import model.Tag;

/**
 *
 * @author Bodnár Tamás <tms.bodnar@gmail.com> | www.kalandlabor.hu
 */
public class jdTagSzerkeszt extends javax.swing.JDialog {
        private Tag tag;
        private boolean mentes;
        
    /**
     * Creates new form jdTagHozzaad
     */
    public jdTagSzerkeszt(java.awt.Frame parent, boolean modal, Tag tag) {
        super(parent, modal);
        initComponents();
        this.tag = tag;
        this.mentes = false;
        if ( tag == null){
            setTitle("Új tag felvétele");
        }else{
            setTitle("Tag szerkesztése");
            jtUjNev.setText(tag.getNev());
            jtUjEmail.setText(tag.getEmail());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtUjNev = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtUjEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbMentes = new javax.swing.JButton();
        jbMegsem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Uj tag hozzáadása");

        jtUjNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUjNevActionPerformed(evt);
            }
        });

        jLabel1.setText("Név:");

        jLabel2.setText("E-mail:");

        jbMentes.setText("Mentés");
        jbMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMentesActionPerformed(evt);
            }
        });

        jbMegsem.setText("Mégsem");
        jbMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMegsemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtUjNev, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(jtUjEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMegsem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbMentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtUjNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbMentes))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMegsem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtUjEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbMegsemActionPerformed

    private void jbMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMentesActionPerformed
        mentes = true;
        if(tag == null){
            tag = new Tag();
        }
        tag.setNev(jtUjNev.getText());
        tag.setEmail(jtUjEmail.getText());
        setVisible(false);
    }//GEN-LAST:event_jbMentesActionPerformed

    private void jtUjNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUjNevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUjNevActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbMegsem;
    private javax.swing.JButton jbMentes;
    private javax.swing.JTextField jtUjEmail;
    private javax.swing.JTextField jtUjNev;
    // End of variables declaration//GEN-END:variables

    public Tag getTag() {
        return tag;
    }

    public boolean isMentes() {
        return mentes;
    }
}
